### ISSUE TITLE
Update to new REST API Plugin from Openfire

### ISSUE THREAD

**Issue by Redor** [Globility/userservice-client#1]
Could you please update your userservice client which is based on userservice v2 API to the REST API plugin?
The user service v2 is build in REST API from openfire. So the only change would be only the path to the new plugin, but provide much more features. 
See here: http://www.igniterealtime.org/projects/openfire/plugins/restapi/readme.html

**Comment by leonroy** [comment]
Thanks for the heads up! Super busy, but will try and do this soon as!
